# kalamine keyboard layout descriptor
name        = "futhorc"  # full layout name, displayed in the keyboard settings
name8       = "futhorc"         # short Windows filename: no spaces, no special chars
locale      = "en"             # locale/language id
variant     = "futhorc"         # layout variant id
author      = "nobody"         # author name
description = "modern FUÞORC layout"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "1.0"
geometry    = "ISO"

base = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│ ~   │ !   │ @   │ #   │ $   │ %   │ ^   │ &   │ *   │ (   │ )   │ _   │ +   ┃          ┃
│ `   │ 1   │ 2   │ 3   │ 4   │ 5   │ 6   │ 7   │ 8   │ 9   │ 0   │ -   │ =   ┃ ⌫        ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃     │     │ ᛠ   │     │ ᚦ   │ ᛄ   │ ᚣ   │ ᛇ   │ ᛟ   │     │ {   │ }   ┃       ┃
┃ ↹      ┃ ᛢ   │ ᚹ   │ ᛖ   │ ᚱ   │ ᛏ   │ ᛡ   │ ᚢ   │ ᛁ   │ ᚩ   │ ᛈ   │ [   │ ]   ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃ ᚪ   │ ᛥ   │     │     │ ᛤ   │     │     │     │     │ :   │ "   │ |   ┃      ┃
┃ ⇬       ┃ ᚫ   │ ᛋ   │ ᛞ   │ ᚠ   │ ᚸ   │ ᚻ   │ ᚷ   │ ᛣ   │ ᛚ   │ ;   │ '   │ \   ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃ |   │     │     │     │     │     │ ᛝ   │     │ <   │ >   │ ?   ┃               ┃
┃ ⇧    ┃ \   │ ᛉ   │     │ ᚳ   │     │ ᛒ   │ ᚾ   │ ᛗ   │ ‍   │ ᛫   │ /   ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''
